Added Kudos Model
konrad04-1989/RubyEmployeeRecognition pull request #3
Opened 2021-12-21 23:19 UTC by konrad04-1989

2022-01-03 13:55 UTC, ciejj requested changes
Really nice job!
I have suggested couple of really small changes. 
Let me know if you have any questions

Also, could you please paste the task description to the PR description? (for next PRs) - it will make the review easier :)

2022-01-03 13:55 UTC, ciejj commented on app/controllers/kudos_controller.rb
> +  before_action :set_kudo, only: %i[show edit update destroy]
FYI - no-one is actually using callbacks (besides authentication) - it is actually making a code harder to read.
Let's leave it like this for now

2022-01-03 13:55 UTC, ciejj commented on app/models/kudo.rb
> +  validates :receiver_id, presence: true
you don't need this - the `belongs_to` is already taking care of that by default

If you do not add  `optional: true` option to `belongs_to` it is expecting Kudo to have that association

2022-01-03 13:55 UTC, ciejj commented on app/views/kudos/new.html.erb
> +</div>
missing newline at the end of the file - you can configure your IDE to take care of it for you, when you are saving the file :)

2022-01-03 13:55 UTC, ciejj commented on app/views/kudos/show.html.erb
> +</div>
missing newline ;)

2022-01-03 13:55 UTC, ciejj commented on db/seeds.rb
> +employee.save!
you used a loop to create Kudos - maybe you could use one for creating Employees as well?

2022-01-03 13:55 UTC, ciejj commented on db/seeds.rb
> +puts "Kudos table seeding done"
and newline ;)

2022-01-03 22:16 UTC, ciejj commented on db/seeds.rb
> +5.times do
try this in console:
```
5.times do |i|
puts i
end
```

2022-01-03 22:17 UTC, ciejj approved these changes

2022-01-04 10:07 UTC, ciejj approved these changes

2022-01-04 10:15 UTC, oskarlakner approved these changes
it's so nice! I'll show you today my approach to writing seeds :v:

2022-01-16 16:58 UTC, merged