Creating admin panel
konrad04-1989/RubyEmployeeRecognition pull request #7
Opened 2022-02-18 21:48 UTC by konrad04-1989

2022-02-22 18:31 UTC, ciejj requested changes
You did a great job, but I am afraid, that some of it was unnecessary :/ 
In my understanding you have implemented an option to login as an employee or admin, but at this point you should not really care about it - there rather should be a seprate /admin path that requires admin credential.

We would need Oskar's confirmation on this ;)

2022-02-22 18:31 UTC, ciejj commented on spec/factories/admins.rb
> +    email { 'admin@admin.com' }
I suggest using sequence here - just like for the user

2022-02-22 18:31 UTC, ciejj commented on spec/system/admin_system_spec.rb
> +    expect(page).to have_text('Signed in successfully.')
It would be good to check not only the notification, but also the landing page

2022-02-22 18:31 UTC, ciejj commented on db/seeds.rb
> +    admin.save!
Consider using  `create!` method instead.
Also - do you really need to provide the `password_confirmation` during the object creation? 

```suggestion
    admin.create!(email: 'admin@rera.com', password: 'zaq123')
```

2022-02-22 18:31 UTC, ciejj commented on config/routes.rb
> +  devise_for :employees, path: 'employees'
I think, that specifying path in both is not really necessary

2022-02-22 18:31 UTC, ciejj commented on app/views/shared/_navbar.html.erb
> +        <% elsif admin_signed_in? %>
This should go to another (admin) navbar - in my understanding on the main page we are just checking if user is logged in

2022-02-22 18:31 UTC, ciejj commented on app/controllers/concerns/accessible.rb
> +module Accessible
I do not think we need this module at all, also it rather should go to the app/concerns folder, not controllers :)

2022-02-22 18:31 UTC, ciejj commented on config/routes.rb
> +  authenticated :admin do
it should be `namespace` - you should be able to access that path, and login afterwards

2022-03-02 00:34 UTC, konrad04-1989 commented
@ciejj  please take a look if you will have a moment. I have made the changes as per the comments above. It seems to me that it is now working as intended ;)

2022-03-05 14:08 UTC, ciejj approved these changes
Looks good - I would only consider using separate layout for admin panel

2022-03-05 21:26 UTC, oskarlakner approved these changes
well done Konrad!

2022-03-07 20:17 UTC, konrad04-1989 commented
Thanks Guys for the approve!
@ciejj   I'll correct separate layout for admin in the next sprint.

2022-03-07 20:17 UTC, merged